export default {
    defaultColor: '#b2b2b2',
    backgroundTransparent: 'transparent',
    defaultBlue: '#0084ff',
    leftBubbleBackground: '#f0f0f0',
    white: '#fff',
    carrot: '#e67e22',
    emerald: '#2ecc71',
    peterRiver: '#3498db',
    wisteria: '#8e44ad',
    alizarin: '#e74c3c',
    turquoise: '#1abc9c',
    midnightBlue: '#2c3e50',
    optionTintColor: '#007AFF',
    timeTextColor: '#aaa',

    themeColor: '#0081cc',
    whiteColor: 'white',
    leftBubbleColor: '#ffffff' ,
    rightBubbleColor: '#0081cc',
    BubbleBackgroundColor: '#e7e7e7' ,
    lightBubbleBackgroundColor :'#0084ff',
};